### ISSUE TITLE
x

### ISSUE THREAD

**Issue by ch4og** [SWL26/draingirls#1]

**Comment by SWL26** [comment]
Здравствуйте, сайт специально сделан таким. Я когда поблизости не нахожу
подъезд, в котором всегда хочется срать, я захожу на этот сайт и сру прям
на публике. С уважением, поддержка Drain Community.

ср, 8 дек. 2021 г., 20:01 Nikita Mitasov ***@***.***>:

**Comment by ch4og** [comment]
Спасибо, я обосрался

**Comment by SWL26** [comment]
Are you pooping? I know you are pooping...😼

чт, 9 дек. 2021 г., 04:34 Nikita Mitasov ***@***.***>:
